development:
  adapter: postgresql
  database: listservice_dev
  pool: 5
  host: localhost

test: &test
  adapter: postgresql
  database: listservice_test
  pool: 5
  host: localhost

staging:
  adapter: 
  database: 
  host: 

production:
  adapter:
  database:
  host: 

